query pastLaunches($limit: Int!, $offset: Int = 0, $sort: String) {
  launchesPast (limit: $limit, offset: $offset, sort: $sort) {
    ...launchesPastIdFragment
    mission_name
    links {
      flickr_images
      mission_patch
    }
  }
}
