query pastLaunches($limit: Int!, $offset: Int = 0) {
  launchesPast (limit: $limit, offset: $offset) {
    ...launchesPastIdFragment
    mission_name
    links {
      flickr_images
      mission_patch
    }
  }
}
